/** 1-bit Grok Bot mark, padded to 384 dots for 58 mm ESC/POS. */
export const GROKBOT_LOGO_WIDTH = 384;
export const GROKBOT_LOGO_HEIGHT = 69;
export const GROKBOT_LOGO_BASE64 =
  "AAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAB///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAf////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAH//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////gAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////wAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////+H4AAAAAAAH//wA" +
  "AAAAAAAAAAAAP4AAAAAAB////gAAAAAAAAAAAAAAAAAD/////+B8AAAAAAAf//8AAAAAAAAAAAAAf8AAAAAAB////4AAAAAAAAAAAAAAAAAH/////+A+AAAA" +
  "AAB////AAAAAAAAAAAAAf8AAAAAAB////+AAAAAAAAAAAAAAAAAP//////A/AAAAAAH////gAAAAAAAAAAAAf8AAAAAAB/////gAAAAAAAAAAAAAAAAf////" +
  "//gfgAAAAAP////4AAAAAAAAAAAAf8AAAAAAB/////wAAAAAAAAf4AAAAAAf//////gPwAAAAAf////8AAAAAAAAAAAAf8AAAAAAB/////4AAAAAAAAf4AAA" +
  "AAA///////wP4AAAAA/////+AAAAAAAAAAAAf8AAAAAAB/////4AAAAAAAAf4AAAAAB////wP/4H4AAAAB//gD//AAAAAAAAAAAAf8AAAAAAB/wAB/8AAAAA" +
  "AAAf4AAAAAB////gH/8D8AAAAD/+AAf/AAAAAAAAAAAAf8AAAAAAB/wAA/8AAAAAAAAf4AAAAAB////gH/+D8AAAAD/4AAP/gAAAAAAAAAAAf8AAAAAAB/wA" +
  "Af8AAAAAAAAf4AAAAAD////gD/+B+AAAAH/wAAD/gAAAAAAAAAAAf8AAAAAAB/wAAP+AAAAAAAAf4AAAAAD////gB//B+AAAAP/gAAB/wAAAAAAAAAAAf8AA" +
  "AAAAB/wAAP+AAAAAAAAf4AAAAAH////wB//B/AAAAP/AAAB/4AAAAAAAAAAAf8AAAAAAB/wAAH+AAAAAAAAf4AAAAAP////wA//h/AAAAP+AAAA/4AAAHAAH" +
  "/wAAf8AAAIAAB/wAAH+AAB/+AAQ/8EAAAAP////4Af/7/AAAAf+AAAA/4D/B/gA//+AAf8AA/8AAB/wAAH+AAH//gAf///AAAAP////8Af///gAAAf8AAAAf" +
  "8H/H/gD///AAf8AB/4AAB/wAAH8AAf//4Af///AAAAf////8AP///gAAA/8AAAAf4H/P/gH///gAf8AD/wAAB/wAAP8AA///8Af///AAAAf////+AP///gAA" +
  "A/4AAAAAAH/P/gf///4Af8AH/gAAB/wAAP8AB////Af///AAAAf/////AP///wAAA/8AAAAAAH+f/gf///8Af8AP/AAAB/wAAf4AH////gf///AAAAf/////" +
  "AP///wAAA/4AAAAAAH///g////8Af8Af+AAAB/wAA/4AP////wf///AAAAf/////gP///wAAA/4AAAAAAH///h/+B/+Af8A/8AAAB/wAD/wAP/gP/wf//+AA" +
  "AAf/////wf///wAAA/4AAAAAAH//wD/4Af/Af8B/4AAAB/////gAf+AD/4Af4AAAAA//////4////wAAA/4AAAAAAH/+AD/wAH/gf8D/wAAAB/////AAf8AB" +
  "/8Af4AAAAA///////////wAAB/wAAAAAAH/4AH/AAD/gf8H/gAAAB////8AA/4AA/8Af4AAAAA///////////wAAB/wAA///8H/wAH/AAD/gf8P/AAAAB///" +
  "/+AA/4AAf8Af4AAAAA///////////wAAB/wAA///8H/wAP+AAB/wf8f+AAAAB/////gB/wAAP+Af4AAAAA///////////wAAB/wAB///+H/gAP+AAB/wf8/8" +
  "AAAAB/////4B/wAAP+Af4AAAAA///////////wAAA/4AB///8H/AAP+AAA/wf9/4AAAAB/////4B/gAAH+Af4AAAAAf//////////wAAA/4AB///8H/AAP+A" +
  "AA/4f//wAAAAB/wAB/+B/gAAH+Af4AAAAAf//////////wAAA/4AB///8H/AAP8AAA/4f//gAAAAB/wAAP+D/gAAH+Af4AAAAAf//////////wAAA/4AA///" +
  "8H/AAP8AAA/4f//wAAAAB/wAAH/D/gAAH+Af4AAAAAf//////////wAAA/4AAAAP8H/AAP8AAA/4f//4AAAAB/wAAD/j/gAAH+Af4AAAAAf//////////gAA" +
  "A/4AAAAP8H/AAP8AAA/4f//4AAAAB/wAAD/j/gAAH+Af4AAAAAf//////////gAAA/8AAAAf8H/AAP8AAA/4f//8AAAAB/wAAD/j/gAAH+Af4AAAAAf/////" +
  "/////gAAAf8AAAAf8H/AAP8AAA/4f//+AAAAB/wAAB/h/gAAH+Af4AAAAAP//////////gAAAf8AAAAf8H/AAP8AAA/wf/P/AAAAB/wAAB/h/gAAH+Af4AAA" +
  "AAP//////////AAAAf+AAAAf4H/AAP8AAA/wf+H/AAAAB/wAAB/x/gAAH+Af4AAAAAH//////////AAAAf+AAAA/4H/AAP+AAB/wf8H/gAAAB/wAAB/h/wAA" +
  "P+Af4AAAAAH/////////+AAAAP/AAAA/wH/AAP+AAB/wf8D/wAAAB/wAAD/h/wAAP8Af4AAAAAD/////////+AAAAP/gAAB/wH/AAH+AAB/wf8B/4AAAB/wA" +
  "AD/g/4AAP8Af4AAAAAD/////////8AAAAH/wAAD/gH/AAH/AAD/gf8A/4AAAB/wAAD/g/4AAf8Af4AAAAAD/////////8AAAAD/4AAH/gH/AAH/gAH/gf8A/" +
  "8AAAB/wAAH/g/8AA/8Af8AAAAAB/////////4AAAAD/8AAf/AH/AAD/wAP/Af8Af+AAAB/wAAP/Af+AB/4Af8AAAAAB/////////4AAAAB//wB/+AH/AAB/4" +
  "A//Af8AP+AAAB/wAB//Af/AD/wAf+AAAAAA/////////4AAAAA/////+AH/AAA//n/+Af8AH/AAAB/////+AP/4//wAP//AAAAAf////////wAAAAAf////8" +
  "AH/AAA////8Af8AH/gAAB/////8AH////gAP//AAAAAP////////gAAAAAP////4AH/AAAf///4Af8AD/wAAB/////4AD////AAP//AAAAAP////////AAAA" +
  "AAH////wAH/AAAP///wAf8AD/4AAB/////wAB///+AAH//AAAAAH///////+AAAAAAD////AAH/AAAH///gAf8AB/4AAB/////gAA///4AAD//AAAAAD////" +
  "///8AAAAAAAP//8AAH/AAAA//+AAf8AA/8AAB////+AAAP//4AAB//AAAAAB///////4AAAAAAAD//wAAH+AAAAP/4AAP8AAf8AAA////gAAAB/+AAAAf+AA" +
  "AAAA///////wAAAAAAAAD4AAAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAFQAAAAAgAAAAAAP//////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAH//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAf////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//gAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

export function grokbotLogoRaster(): Buffer {
  return Buffer.from(GROKBOT_LOGO_BASE64, "base64");
}
